FROM jenkins/jenkins:lts

USER root

# Instalación de Docker CLI para poder construir imágenes desde Jenkins
RUN apt-get update && apt-get install -y \
    docker.io \
    curl \
    gnupg \
    unzip \
    git \
    sudo \
    && rm -rf /var/lib/apt/lists/*

# Crear usuario jenkins dentro del grupo docker
RUN usermod -aG docker jenkins

# Instalar Gradle
ENV GRADLE_VERSION=8.5
RUN mkdir /opt/gradle \
    && curl -sL https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -o gradle.zip \
    && unzip gradle.zip -d /opt/gradle \
    && ln -s /opt/gradle/gradle-${GRADLE_VERSION}/bin/gradle /usr/bin/gradle \
    && rm gradle.zip

# Instalar Node.js y npm (para usar Newman si vas a correr Postman tests)
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs

# Instalar Newman (para pruebas Postman)
RUN npm install -g newman

#Agregar plugin CLI de Jenkins
RUN jenkins-plugin-cli --plugins "workflow-aggregator git docker-workflow" --verbose

# Establecer permisos correctos
RUN chown -R jenkins:jenkins /var/jenkins_home

USER jenkins
